version: '2'
services:
    yarn:
        image: node:8.10
        env_file: .env
        entrypoint: yarn
        command: run start:dev
        ports:
            - "$PORT:$PORT"
        working_dir: /app
        volumes:
            - .:/app
